### ISSUE TITLE
simplesvg bug with expression function

### ISSUE THREAD

**Issue by acqueron** [rduivenvoorde/simplesvg#13]
I have a bug 2016-02-15T11:07:44    1   Traceback (most recent call last):
              File "C:/Users/y.moreno/.qgis2/python/plugins\simplesvg\SimpleSvg.py", line 143, in writeToFile
                output = self.writeSVG()
              File "C:/Users/y.moreno/.qgis2/python/plugins\simplesvg\SimpleSvg.py", line 208, in writeSVG
                svg.extend(self.writeVectorLayer(layer, False))
              File "C:/Users/y.moreno/.qgis2/python/plugins\simplesvg\SimpleSvg.py", line 368, in writeVectorLayer
                labeltxt = self.sanitizeStr(feature[lblSettings.fieldName])
            KeyError: ' concat( "NOM_COM")'

**Comment by rduivenvoorde** [comment]
Too old to reproduce
