### ISSUE TITLE
AttributeError: type object 'GeometryType' has no attribute 'LineGeometry'

### ISSUE THREAD

**Issue by carlostighe** [rduivenvoorde/simplesvg#18]
Trying to export a shapefile to svg and run into this error:  
```  
Traceback (most recent call last):
  File "/home/carlos/.local/share/QGIS/QGIS3/profiles/default/python/plugins/simplesvg/SimpleSvg.py", line 155, in writeToFile
    output = self.writeSVG()
  File "/home/carlos/.local/share/QGIS/QGIS3/profiles/default/python/plugins/simplesvg/SimpleSvg.py", line 214, in writeSVG
    svg.extend(self.writeVectorLayer(layer, False))
  File "/home/carlos/.local/share/QGIS/QGIS3/profiles/default/python/plugins/simplesvg/SimpleSvg.py", line 336, in writeVectorLayer
    sym = self.createSymbol(feature, symbol, layer)
  File "/home/carlos/.local/share/QGIS/QGIS3/profiles/default/python/plugins/simplesvg/SimpleSvg.py", line 433, in createSymbol
    if QgsWkbTypes.geometryType(geom.wkbType())  == QgsWkbTypes.GeometryType.LineGeometry:
AttributeError: type object 'GeometryType' has no attribute 'LineGeometry'  
```  

I have also coverted it from polygon to line (vector -> geometry tools -> polygons to lines) and then trying but run into the same error.   

Running 
QGIS 3.0 on docker on Ubuntu 18.04

**Comment by rduivenvoorde** [comment]
@carlostighe can share (a part) of you data and or your QGIS project?

Also QGIS 3.0 is really old. Please check in a newer version of QGIS (we are on 3.20 now....)

QgsWkbTypes.GeometryType.LineGeometry is a constant which if you put it in the Python console of QGIS should show 'one'

![Screenshot-20210829115137-476x179](https://user-images.githubusercontent.com/731673/131246232-d701363b-71ca-48d0-ac53-bdbb1211c241.png)

**Comment by carlostighe** [comment]
Thats odd. I entered the above into the python console and get the same error. 
I had issues with installing QGIS on ubuntu and ran it via docker to get around them but that might be the problem. 
Im going to look at a direct install again and Ill follow up.
