### ISSUE TITLE
OverflowError: cannot convert float infinity to integer

### ISSUE THREAD

**Issue by acer9997** [rduivenvoorde/simplesvg#8]
When I try to save the file, this error message appears: 

```
An error has occured while executing Python code:


Traceback (most recent call last):
  File "/Users/acer9997/.qgis2/python/plugins/simplesvg/SimpleSvg.py", line 143, in writeToFile
    output = self.writeSVG()
  File "/Users/acer9997/.qgis2/python/plugins/simplesvg/SimpleSvg.py", line 225, in writeSVG
    svg.extend(self.writeVectorLayer(layer, True))
  File "/Users/acer9997/.qgis2/python/plugins/simplesvg/SimpleSvg.py", line 384, in writeVectorLayer
    svg.extend(self.label2svg(geom.asPoint(), id+str(i), self.symbolForFeature(layer, feature), labeltxt))
  File "/Users/acer9997/.qgis2/python/plugins/simplesvg/SimpleSvg.py", line 507, in label2svg
    xy =  self.w2p(point.x(), point.y(), self.iface.mapCanvas().mapUnitsPerPixel(), self.currentExtent.xMinimum(), self.currentExtent.yMaximum())
  File "/Users/acer9997/.qgis2/python/plugins/simplesvg/SimpleSvg.py", line 714, in w2p
    return [int(pixX), int(-pixY)]
OverflowError: cannot convert float infinity to integer


Python version:
2.7.6 (default, Sep  9 2014, 15:04:36) 
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.39)]


QGIS version:
2.8.2-Wien Wien, 

Python path: ['/Applications/QGIS.app/Contents/MacOS/../Resources/python/plugins/processing', '/Applications/QGIS.app/Contents/MacOS/../Resources/python', u'/Users/acer9997/.qgis2/python', u'/Users/acer9997/.qgis2/python/plugins', '/Applications/QGIS.app/Contents/MacOS/../Resources/python/plugins', '/Library/Frameworks/SQLite3.framework/Versions/C/Python/2.7', '/Library/Frameworks/GEOS.framework/Versions/3/Python/2.7/site-packages', '/Library/Python/2.7/site-packages/numpy-override', '/Library/Python/2.7/site-packages/matplotlib-override', '/Library/Frameworks/GDAL.framework/Versions/1.11/Python/2.7/site-packages', '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python27.zip', '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7', '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-darwin', '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac', '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac/lib-scriptpackages', '/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python', '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-tk', '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-old', '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload', '/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/PyObjC', '/Library/Python/2.7/site-packages', u'/Users/acer9997/.qgis2//python', '/Applications/QGIS.app/Contents/Resources/python/plugins/fTools/tools', '/Users/acer9997/Dropbox/Projects/Ethanol Capacity Map']
```

**Comment by acer9997** [comment]
Please disregard - this appears to be the result of a corrupt shape file.

**Comment by rduivenvoorde** [comment]
@acer9997 ok, thanks, You can close this issue yourself.
